# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: perception.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'perception.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10perception.proto\x12\rai.perception\x1a\x1fgoogle/protobuf/timestamp.proto\"K\n\x11GetRawFlowRequest\x12\x10\n\x08store_id\x18\x01 \x01(\x05\x12\x12\n\nstart_time\x18\x02 \x01(\t\x12\x10\n\x08\x65nd_time\x18\x03 \x01(\t\"\xc9\x02\n\x12GetRawFlowResponse\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x43\n\tflow_list\x18\x03 \x03(\x0b\x32\x30.ai.perception.GetRawFlowResponse.AiCustomerItem\x1a\xce\x01\n\x0e\x41iCustomerItem\x12\x16\n\x0e\x61i_customer_id\x18\x01 \x01(\x03\x12\x10\n\x08store_id\x18\x02 \x01(\x05\x12\x1b\n\x13\x63ustomer_start_time\x18\x03 \x01(\t\x12\x19\n\x11\x63ustomer_end_time\x18\x04 \x01(\t\x12\x1c\n\x14\x63ustomer_enter_total\x18\x05 \x01(\x05\x12\x1c\n\x14\x63ustomer_leave_total\x18\x06 \x01(\x05\x12\x1e\n\x16\x61i_customer_stats_time\x18\x07 \x01(\t2p\n\x13\x41iPerceptionService\x12Y\n\x12GetRawCustomerFlow\x12 .ai.perception.GetRawFlowRequest\x1a!.ai.perception.GetRawFlowResponseB\x1cZ\x1a./pb/perception;perceptionb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'perception_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\032./pb/perception;perception'
  _globals['_GETRAWFLOWREQUEST']._serialized_start=68
  _globals['_GETRAWFLOWREQUEST']._serialized_end=143
  _globals['_GETRAWFLOWRESPONSE']._serialized_start=146
  _globals['_GETRAWFLOWRESPONSE']._serialized_end=475
  _globals['_GETRAWFLOWRESPONSE_AICUSTOMERITEM']._serialized_start=269
  _globals['_GETRAWFLOWRESPONSE_AICUSTOMERITEM']._serialized_end=475
  _globals['_AIPERCEPTIONSERVICE']._serialized_start=477
  _globals['_AIPERCEPTIONSERVICE']._serialized_end=589
# @@protoc_insertion_point(module_scope)
