# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from traffic_sense.proto import perception_pb2 as perception__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in perception_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AiPerceptionServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetRawCustomerFlow = channel.unary_unary(
                '/ai.perception.AiPerceptionService/GetRawCustomerFlow',
                request_serializer=perception__pb2.GetRawFlowRequest.SerializeToString,
                response_deserializer=perception__pb2.GetRawFlowResponse.FromString,
                _registered_method=True)


class AiPerceptionServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetRawCustomerFlow(self, request, context):
        """数据分析微服务/Go 调用：跨微服务获取底层客流数据，用于预测第二天销售额或对话 Prompt
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AiPerceptionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetRawCustomerFlow': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRawCustomerFlow,
                    request_deserializer=perception__pb2.GetRawFlowRequest.FromString,
                    response_serializer=perception__pb2.GetRawFlowResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ai.perception.AiPerceptionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ai.perception.AiPerceptionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AiPerceptionService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetRawCustomerFlow(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.perception.AiPerceptionService/GetRawCustomerFlow',
            perception__pb2.GetRawFlowRequest.SerializeToString,
            perception__pb2.GetRawFlowResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
