# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: store_business_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'store_business_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cstore_business_service.proto\x12\rstorebusiness\"\x8f\x01\n\x17PushCustomerFlowRequest\x12\x10\n\x08store_id\x18\x01 \x01(\x05\x12\x18\n\x10record_timestamp\x18\x02 \x01(\t\x12\x1b\n\x13\x63ustomer_start_time\x18\x03 \x01(\t\x12\x19\n\x11\x63ustomer_end_time\x18\x04 \x01(\t\x12\x10\n\x08in_count\x18\x05 \x01(\x05\"+\n\x18PushCustomerFlowResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32{\n\x14StoreBusinessService\x12\x63\n\x10PushCustomerFlow\x12&.storebusiness.PushCustomerFlowRequest\x1a\'.storebusiness.PushCustomerFlowResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'store_business_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PUSHCUSTOMERFLOWREQUEST']._serialized_start=48
  _globals['_PUSHCUSTOMERFLOWREQUEST']._serialized_end=191
  _globals['_PUSHCUSTOMERFLOWRESPONSE']._serialized_start=193
  _globals['_PUSHCUSTOMERFLOWRESPONSE']._serialized_end=236
  _globals['_STOREBUSINESSSERVICE']._serialized_start=238
  _globals['_STOREBUSINESSSERVICE']._serialized_end=361
# @@protoc_insertion_point(module_scope)
