# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from ai_assistant.proto import ai_analysis_pb2 as ai__analysis__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in ai_analysis_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AiAnalysisAndChatServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.TriggerDailyAnalysis = channel.unary_unary(
                '/ai.analysis.AiAnalysisAndChatService/TriggerDailyAnalysis',
                request_serializer=ai__analysis__pb2.TriggerAnalysisRequest.SerializeToString,
                response_deserializer=ai__analysis__pb2.TriggerAnalysisResponse.FromString,
                _registered_method=True)
        self.GetAnalysisReport = channel.unary_unary(
                '/ai.analysis.AiAnalysisAndChatService/GetAnalysisReport',
                request_serializer=ai__analysis__pb2.GetAnalysisRequest.SerializeToString,
                response_deserializer=ai__analysis__pb2.GetAnalysisResponse.FromString,
                _registered_method=True)
        self.GetSalesForecast = channel.unary_unary(
                '/ai.analysis.AiAnalysisAndChatService/GetSalesForecast',
                request_serializer=ai__analysis__pb2.GetSalesForecastRequest.SerializeToString,
                response_deserializer=ai__analysis__pb2.GetSalesForecastResponse.FromString,
                _registered_method=True)


class AiAnalysisAndChatServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def TriggerDailyAnalysis(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAnalysisReport(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSalesForecast(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AiAnalysisAndChatServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'TriggerDailyAnalysis': grpc.unary_unary_rpc_method_handler(
                    servicer.TriggerDailyAnalysis,
                    request_deserializer=ai__analysis__pb2.TriggerAnalysisRequest.FromString,
                    response_serializer=ai__analysis__pb2.TriggerAnalysisResponse.SerializeToString,
            ),
            'GetAnalysisReport': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAnalysisReport,
                    request_deserializer=ai__analysis__pb2.GetAnalysisRequest.FromString,
                    response_serializer=ai__analysis__pb2.GetAnalysisResponse.SerializeToString,
            ),
            'GetSalesForecast': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSalesForecast,
                    request_deserializer=ai__analysis__pb2.GetSalesForecastRequest.FromString,
                    response_serializer=ai__analysis__pb2.GetSalesForecastResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ai.analysis.AiAnalysisAndChatService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ai.analysis.AiAnalysisAndChatService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AiAnalysisAndChatService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def TriggerDailyAnalysis(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.analysis.AiAnalysisAndChatService/TriggerDailyAnalysis',
            ai__analysis__pb2.TriggerAnalysisRequest.SerializeToString,
            ai__analysis__pb2.TriggerAnalysisResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAnalysisReport(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.analysis.AiAnalysisAndChatService/GetAnalysisReport',
            ai__analysis__pb2.GetAnalysisRequest.SerializeToString,
            ai__analysis__pb2.GetAnalysisResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSalesForecast(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.analysis.AiAnalysisAndChatService/GetSalesForecast',
            ai__analysis__pb2.GetSalesForecastRequest.SerializeToString,
            ai__analysis__pb2.GetSalesForecastResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
