# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from ai_assistant.proto import basic_data_service_pb2 as basic__data__service__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in basic_data_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BasicDataServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetSkuDictionary = channel.unary_unary(
                '/basicdata.BasicDataService/GetSkuDictionary',
                request_serializer=basic__data__service__pb2.SkuDictRequest.SerializeToString,
                response_deserializer=basic__data__service__pb2.SkuDictResponse.FromString,
                _registered_method=True)
        self.GetStoreContext = channel.unary_unary(
                '/basicdata.BasicDataService/GetStoreContext',
                request_serializer=basic__data__service__pb2.StoreContextRequest.SerializeToString,
                response_deserializer=basic__data__service__pb2.StoreContextResponse.FromString,
                _registered_method=True)


class BasicDataServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetSkuDictionary(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStoreContext(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BasicDataServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetSkuDictionary': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSkuDictionary,
                    request_deserializer=basic__data__service__pb2.SkuDictRequest.FromString,
                    response_serializer=basic__data__service__pb2.SkuDictResponse.SerializeToString,
            ),
            'GetStoreContext': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStoreContext,
                    request_deserializer=basic__data__service__pb2.StoreContextRequest.FromString,
                    response_serializer=basic__data__service__pb2.StoreContextResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'basicdata.BasicDataService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('basicdata.BasicDataService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BasicDataService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetSkuDictionary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/basicdata.BasicDataService/GetSkuDictionary',
            basic__data__service__pb2.SkuDictRequest.SerializeToString,
            basic__data__service__pb2.SkuDictResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStoreContext(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/basicdata.BasicDataService/GetStoreContext',
            basic__data__service__pb2.StoreContextRequest.SerializeToString,
            basic__data__service__pb2.StoreContextResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
