# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from ai_assistant.proto import store_business_service_pb2 as store__business__service__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in store_business_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class StoreBusinessServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetBusinessSnapshot = channel.unary_unary(
                '/storebusiness.StoreBusinessService/GetBusinessSnapshot',
                request_serializer=store__business__service__pb2.SnapshotRequest.SerializeToString,
                response_deserializer=store__business__service__pb2.SnapshotResponse.FromString,
                _registered_method=True)
        self.PushCustomerFlow = channel.unary_unary(
                '/storebusiness.StoreBusinessService/PushCustomerFlow',
                request_serializer=store__business__service__pb2.PushCustomerFlowRequest.SerializeToString,
                response_deserializer=store__business__service__pb2.PushCustomerFlowResponse.FromString,
                _registered_method=True)
        self.SyncInventoryDiagnosis = channel.unary_unary(
                '/storebusiness.StoreBusinessService/SyncInventoryDiagnosis',
                request_serializer=store__business__service__pb2.SyncDiagnosisRequest.SerializeToString,
                response_deserializer=store__business__service__pb2.SyncDiagnosisResponse.FromString,
                _registered_method=True)
        self.CreateAITransferOrder = channel.unary_unary(
                '/storebusiness.StoreBusinessService/CreateAITransferOrder',
                request_serializer=store__business__service__pb2.CreateAiTransferRequest.SerializeToString,
                response_deserializer=store__business__service__pb2.CreateAiTransferResponse.FromString,
                _registered_method=True)


class StoreBusinessServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetBusinessSnapshot(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PushCustomerFlow(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SyncInventoryDiagnosis(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateAITransferOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StoreBusinessServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetBusinessSnapshot': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBusinessSnapshot,
                    request_deserializer=store__business__service__pb2.SnapshotRequest.FromString,
                    response_serializer=store__business__service__pb2.SnapshotResponse.SerializeToString,
            ),
            'PushCustomerFlow': grpc.unary_unary_rpc_method_handler(
                    servicer.PushCustomerFlow,
                    request_deserializer=store__business__service__pb2.PushCustomerFlowRequest.FromString,
                    response_serializer=store__business__service__pb2.PushCustomerFlowResponse.SerializeToString,
            ),
            'SyncInventoryDiagnosis': grpc.unary_unary_rpc_method_handler(
                    servicer.SyncInventoryDiagnosis,
                    request_deserializer=store__business__service__pb2.SyncDiagnosisRequest.FromString,
                    response_serializer=store__business__service__pb2.SyncDiagnosisResponse.SerializeToString,
            ),
            'CreateAITransferOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateAITransferOrder,
                    request_deserializer=store__business__service__pb2.CreateAiTransferRequest.FromString,
                    response_serializer=store__business__service__pb2.CreateAiTransferResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'storebusiness.StoreBusinessService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('storebusiness.StoreBusinessService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class StoreBusinessService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetBusinessSnapshot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/storebusiness.StoreBusinessService/GetBusinessSnapshot',
            store__business__service__pb2.SnapshotRequest.SerializeToString,
            store__business__service__pb2.SnapshotResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PushCustomerFlow(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/storebusiness.StoreBusinessService/PushCustomerFlow',
            store__business__service__pb2.PushCustomerFlowRequest.SerializeToString,
            store__business__service__pb2.PushCustomerFlowResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SyncInventoryDiagnosis(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/storebusiness.StoreBusinessService/SyncInventoryDiagnosis',
            store__business__service__pb2.SyncDiagnosisRequest.SerializeToString,
            store__business__service__pb2.SyncDiagnosisResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateAITransferOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/storebusiness.StoreBusinessService/CreateAITransferOrder',
            store__business__service__pb2.CreateAiTransferRequest.SerializeToString,
            store__business__service__pb2.CreateAiTransferResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
